/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import modelo.Lectura;
import modelo.Medidor;

/**
 *
 * @author enman
 */
public class FacturaView extends javax.swing.JPanel {

    /**
     * Creates new form VistaFactura
     */
    public FacturaView() {
        initComponents();
    }

    public JButton getBtnCalcular() {
        return btnCalcular;
    }

    public void setBtnCalcular(JButton btnCalcular) {
        this.btnCalcular = btnCalcular;
    }

    public JButton getBtnGenerarRecibo() {
        return btnGenerarRecibo;
    }

    public void setBtnGenerarRecibo(JButton btnGenerarRecibo) {
        this.btnGenerarRecibo = btnGenerarRecibo;
    }

    public JComboBox<Medidor> getCbMedidores() {
        return cbMedidores;
    }

    public void setCbMedidores(JComboBox<Medidor> cbMedidores) {
        this.cbMedidores = cbMedidores;
    }

    public JTextField getTxtCodigoMedidor() {
        return txtCodigoMedidor;
    }

    public void setTxtCodigoMedidor(JTextField txtCodigoMedidor) {
        this.txtCodigoMedidor = txtCodigoMedidor;
    }

    public JTextField getTxtConsumo() {
        return txtConsumo;
    }

    public void setTxtConsumo(JTextField txtConsumo) {
        this.txtConsumo = txtConsumo;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtMontoConsumo() {
        return txtMontoConsumo;
    }

    public void setTxtMontoConsumo(JTextField txtMontoConsumo) {
        this.txtMontoConsumo = txtMontoConsumo;
    }

    public JTextField getTxtMontoServicio() {
        return txtMontoServicio;
    }

    public void setTxtMontoServicio(JTextField txtMontoServicio) {
        this.txtMontoServicio = txtMontoServicio;
    }

    public JTextField getTxtNombreCliente() {
        return txtNombreCliente;
    }

    public void setTxtNombreCliente(JTextField txtNombreCliente) {
        this.txtNombreCliente = txtNombreCliente;
    }

    public JDateChooser getDateInicio() {
        return dateInicio;
    }

    public JDateChooser getDateFin() {
        return dateFin;
    }

    public JTextField getTxtTotalPagar() {
        return txtTotalPagar;
    }

    public void setTxtTotalPagar(JTextField txtTotalPagar) {
        this.txtTotalPagar = txtTotalPagar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        cbMedidores = new javax.swing.JComboBox<>();
        txtNombreCliente = new javax.swing.JTextField();
        txtCodigoMedidor = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtConsumo = new javax.swing.JTextField();
        txtMontoConsumo = new javax.swing.JTextField();
        txtMontoServicio = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        btnGenerarRecibo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateInicio = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(cbMedidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 116, 186, -1));

        txtNombreCliente.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreCliente.setEnabled(false);
        txtNombreCliente.setPreferredSize(new java.awt.Dimension(70, 22));
        add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 156, 186, -1));

        txtCodigoMedidor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoMedidor.setEnabled(false);
        txtCodigoMedidor.setPreferredSize(new java.awt.Dimension(70, 22));
        add(txtCodigoMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 196, 186, -1));

        txtDireccion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDireccion.setEnabled(false);
        txtDireccion.setPreferredSize(new java.awt.Dimension(70, 22));
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 239, 186, -1));

        txtConsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConsumo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        add(txtConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 353, 102, -1));

        txtMontoConsumo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoConsumo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMontoConsumo.setEnabled(false);
        add(txtMontoConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 159, 102, -1));

        txtMontoServicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMontoServicio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMontoServicio.setEnabled(false);
        add(txtMontoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 199, 102, -1));

        txtTotalPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalPagar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTotalPagar.setEnabled(false);
        add(txtTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 239, 102, -1));

        btnCalcular.setText("Calcular");
        add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 425, -1, -1));

        btnGenerarRecibo.setText("Generar Factura");
        add(btnGenerarRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 425, -1, -1));

        jLabel1.setText("Nombre del cliente:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, -1, -1));

        jLabel2.setText("Código del Medidor:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 199, -1, -1));

        jLabel3.setText("Dirección");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, -1, -1));

        jLabel4.setText("Fecha de Inicio: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 279, -1, -1));

        jLabel5.setText("Consumo:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 356, -1, -1));

        jLabel6.setText("Monto Consumo ($USD):");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 162, -1, -1));

        jLabel7.setText("Monto Servicio ($USD):");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 202, -1, -1));

        jLabel8.setText("Total ($USD):");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 242, -1, -1));
        add(dateInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 279, 186, -1));
        add(dateFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 313, 186, -1));

        jLabel9.setText("Fecha Fin:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 319, -1, -1));

        jLabel10.setText("Medidores:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 119, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(1060, 105));
        jPanel1.setMinimumSize(new java.awt.Dimension(1060, 105));
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 105));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GENERACION DE FACTURA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(29, 29, 29))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCalcular;
    public javax.swing.JButton btnGenerarRecibo;
    public javax.swing.JComboBox<Medidor> cbMedidores;
    public com.toedter.calendar.JDateChooser dateFin;
    public com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCodigoMedidor;
    public javax.swing.JTextField txtConsumo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtMontoConsumo;
    public javax.swing.JTextField txtMontoServicio;
    public javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtTotalPagar;
    // End of variables declaration//GEN-END:variables

}
