/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import modelo.Factura;

/**
 *
 * @author danie
 */
public class ItemFacturaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemFacturaPanel
     */
    public ItemFacturaPanel(Factura f) {
        initComponents();
        lblNoFactura.setText(String.valueOf(f.getId()));
        lblFechaFactur.setText(String.valueOf(f.getFechaLimite()));
        lblTotalFact.setText(String.valueOf(f.getMontoTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNoFactura = new javax.swing.JLabel();
        lblFechaFactur = new javax.swing.JLabel();
        lblTotalFact = new javax.swing.JLabel();
        btnDetalleFact = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        setForeground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel1.setText("Factura #");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Fecha ");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel3.setText("Monto");

        lblNoFactura.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblNoFactura.setText("jLabel4");

        lblFechaFactur.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblFechaFactur.setText("jLabel4");

        lblTotalFact.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblTotalFact.setText("jLabel4");

        btnDetalleFact.setBackground(new java.awt.Color(102, 102, 102));
        btnDetalleFact.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnDetalleFact.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalleFact.setText("Detalle");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNoFactura)
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblFechaFactur)
                .addGap(92, 92, 92)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalFact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalleFact)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblNoFactura)
                    .addComponent(jLabel2)
                    .addComponent(lblFechaFactur)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblTotalFact))
                    .addComponent(btnDetalleFact))
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblFechaFactur() {
        return lblFechaFactur;
    }

    public JLabel getLblNoFactura() {
        return lblNoFactura;
    }

    public JLabel getLblTotalFact() {
        return lblTotalFact;
    }

    public JButton getBtnDetalleFact() {
        return btnDetalleFact;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleFact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFechaFactur;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel lblTotalFact;
    // End of variables declaration//GEN-END:variables
}
