/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import modelo.Factura;

/**
 *
 * @author danie
 */
public class ItemFacturaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemFacturaPanel
     */
    public ItemFacturaPanel(Factura f) {
        initComponents();
        lblNoFactura.setText(String.valueOf(f.getId()));
        lblFechaFactur.setText(String.valueOf(f.getFechaLimite()));
        lblTotalFact.setText(String.valueOf(f.getMontoTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNoFactura = new javax.swing.JLabel();
        lblFechaFactur = new javax.swing.JLabel();
        lblTotalFact = new javax.swing.JLabel();
        btnDetalleFact = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Factura #");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 54, 0, 0);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Fecha ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 187, 0, 0);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Monto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 191, 0, 0);
        add(jLabel3, gridBagConstraints);

        lblNoFactura.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 54, 0, 0);
        add(lblNoFactura, gridBagConstraints);

        lblFechaFactur.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 187, 0, 0);
        add(lblFechaFactur, gridBagConstraints);

        lblTotalFact.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 190, 0, 0);
        add(lblTotalFact, gridBagConstraints);

        btnDetalleFact.setBackground(new java.awt.Color(204, 204, 255));
        btnDetalleFact.setText("Detalle");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 78, 0, 36);
        add(btnDetalleFact, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblFechaFactur() {
        return lblFechaFactur;
    }

    public JLabel getLblNoFactura() {
        return lblNoFactura;
    }

    public JLabel getLblTotalFact() {
        return lblTotalFact;
    }

    public JButton getBtnDetalleFact() {
        return btnDetalleFact;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleFact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFechaFactur;
    private javax.swing.JLabel lblNoFactura;
    private javax.swing.JLabel lblTotalFact;
    // End of variables declaration//GEN-END:variables
}
