/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class ViewDetalleFactura extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetalleFactura
     */
    public ViewDetalleFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblConsumoDiam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFcehaInic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCodigoMedi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblLimitePago = new javax.swing.JLabel();
        lblMora = new javax.swing.JLabel();
        lblConsumoDin = new javax.swing.JLabel();
        lblMontoServ = new javax.swing.JLabel();
        lblMontoNeto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRealizarPago = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Detalle lectura______________________________________________________________________________________________________________");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Consumo:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 86, -1, -1));

        lblConsumoDiam.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblConsumoDiam.setText("jLabel3");
        add(lblConsumoDiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 86, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 86, -1, -1));

        lblFcehaInic.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFcehaInic.setText("jLabel5");
        add(lblFcehaInic, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 86, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setText("---");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 86, -1, -1));

        lblFechaFin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFechaFin.setText("jLabel7");
        add(lblFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 86, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("SITEMA DE COBRO DE AGUA");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 18, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Detalle Medidor____________________________________________________________________________________________________________");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Codigo:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        lblCodigoMedi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCodigoMedi.setText("jLabel11");
        add(lblCodigoMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setText("Propietario:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        lblPropietario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPropietario.setText("jLabel13");
        add(lblPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Direccion: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblDireccion.setText("jLabel5");
        add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setText("Detalle Factura_____________________________________________________________________________________________________________");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Fecha limite pago:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setText("Mora:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 292, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setText("Consumo:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 292, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setText("Montos");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 264, -1, -1));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel16.setText("Servicio:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 292, -1, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel17.setText("Neto:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 292, -1, -1));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel18.setText("TOTAL:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        lblLimitePago.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblLimitePago.setText("jLabel19");
        add(lblLimitePago, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        lblMora.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMora.setText("jLabel20");
        add(lblMora, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 292, -1, -1));

        lblConsumoDin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblConsumoDin.setText("jLabel21");
        add(lblConsumoDin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 292, -1, -1));

        lblMontoServ.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMontoServ.setText("jLabel22");
        add(lblMontoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 292, -1, -1));

        lblMontoNeto.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMontoNeto.setText("jLabel23");
        add(lblMontoNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 292, -1, -1));

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTotal.setText("jLabel24");
        add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        btnRegresar.setText("Regresar");
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 407, 165, 35));

        btnRealizarPago.setText("Realizar Pago");
        add(btnRealizarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 407, 146, 35));
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblCodigoMedi() {
        return lblCodigoMedi;
    }

    public JLabel getLblConsumo() {
        return lblConsumoDiam;
    }

    public JLabel getLblFcehaInic() {
        return lblFcehaInic;
    }

    public JLabel getLblFechaFin() {
        return lblFechaFin;
    }

    public JLabel getLblPropietario() {
        return lblPropietario;
    }

    public JButton getBtnRealizarPago() {
        return btnRealizarPago;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JLabel getLblConsumoDiam() {
        return lblConsumoDiam;
    }

    public JLabel getLblConsumoDin() {
        return lblConsumoDin;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblLimitePago() {
        return lblLimitePago;
    }

    public JLabel getLblMontoNeto() {
        return lblMontoNeto;
    }

    public JLabel getLblMontoServ() {
        return lblMontoServ;
    }

    public JLabel getLblMora() {
        return lblMora;
    }

    public JLabel getLblTotal() {
        return lblTotal;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCodigoMedi;
    private javax.swing.JLabel lblConsumoDiam;
    private javax.swing.JLabel lblConsumoDin;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFcehaInic;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblLimitePago;
    private javax.swing.JLabel lblMontoNeto;
    private javax.swing.JLabel lblMontoServ;
    private javax.swing.JLabel lblMora;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
