/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author danie
 */
public class ViewDetalleFactura extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetalleFactura
     */
    public ViewDetalleFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblConsumoDiam = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFcehaInic = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCodigoMedi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPropietario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblLimitePago = new javax.swing.JLabel();
        lblMora = new javax.swing.JLabel();
        lblConsumoDin = new javax.swing.JLabel();
        lblMontoServ = new javax.swing.JLabel();
        lblMontoNeto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnRealizarPago = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Detalle lectura______________________________________________________________________________________________________________");
        add(jLabel1);
        jLabel1.setBounds(10, 50, 800, 18);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("Consumo:");
        add(jLabel2);
        jLabel2.setBounds(107, 86, 62, 18);

        lblConsumoDiam.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblConsumoDiam.setText("jLabel3");
        add(lblConsumoDiam);
        lblConsumoDiam.setBounds(190, 86, 45, 18);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Fecha:");
        add(jLabel4);
        jLabel4.setBounds(390, 90, 42, 18);

        lblFcehaInic.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFcehaInic.setText("jLabel5");
        add(lblFcehaInic);
        lblFcehaInic.setBounds(440, 90, 80, 18);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setText("---");
        add(jLabel6);
        jLabel6.setBounds(530, 90, 15, 18);

        lblFechaFin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFechaFin.setText("jLabel7");
        add(lblFechaFin);
        lblFechaFin.setBounds(560, 90, 100, 18);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("SITEMA DE COBRO DE AGUA");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel8);
        jLabel8.setBounds(350, 20, 175, 18);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Detalle Medidor____________________________________________________________________________________________________________");
        add(jLabel9);
        jLabel9.setBounds(10, 130, 810, 18);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Codigo:");
        add(jLabel10);
        jLabel10.setBounds(110, 170, 48, 18);

        lblCodigoMedi.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCodigoMedi.setText("jLabel11");
        add(lblCodigoMedi);
        lblCodigoMedi.setBounds(170, 170, 150, 18);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setText("Propietario:");
        add(jLabel12);
        jLabel12.setBounds(380, 170, 76, 18);

        lblPropietario.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPropietario.setText("jLabel13");
        add(lblPropietario);
        lblPropietario.setBounds(470, 170, 290, 18);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Direccion: ");
        add(jLabel3);
        jLabel3.setBounds(110, 200, 69, 18);

        lblDireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblDireccion.setText("jLabel5");
        add(lblDireccion);
        lblDireccion.setBounds(180, 200, 620, 18);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setText("Detalle Factura_____________________________________________________________________________________________________________");
        add(jLabel7);
        jLabel7.setBounds(10, 220, 810, 18);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Fecha limite pago:");
        add(jLabel11);
        jLabel11.setBounds(520, 340, 116, 18);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setText("Mora:");
        add(jLabel13);
        jLabel13.setBounds(74, 292, 36, 18);

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setText("Consumo:");
        add(jLabel14);
        jLabel14.setBounds(250, 290, 62, 18);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setText("Montos");
        add(jLabel15);
        jLabel15.setBounds(33, 264, 47, 18);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel16.setText("Servicio:");
        add(jLabel16);
        jLabel16.setBounds(470, 290, 55, 18);

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel17.setText("Neto:");
        add(jLabel17);
        jLabel17.setBounds(620, 290, 36, 18);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel18.setText("TOTAL:");
        add(jLabel18);
        jLabel18.setBounds(60, 340, 46, 18);

        lblLimitePago.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblLimitePago.setText("jLabel19");
        add(lblLimitePago);
        lblLimitePago.setBounds(650, 340, 100, 18);

        lblMora.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMora.setText("jLabel20");
        add(lblMora);
        lblMora.setBounds(117, 292, 70, 18);

        lblConsumoDin.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblConsumoDin.setText("jLabel21");
        add(lblConsumoDin);
        lblConsumoDin.setBounds(320, 290, 90, 18);

        lblMontoServ.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMontoServ.setText("jLabel22");
        add(lblMontoServ);
        lblMontoServ.setBounds(540, 290, 70, 18);

        lblMontoNeto.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblMontoNeto.setText("jLabel23");
        add(lblMontoNeto);
        lblMontoNeto.setBounds(660, 290, 80, 18);

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblTotal.setText("jLabel24");
        add(lblTotal);
        lblTotal.setBounds(130, 340, 100, 18);

        btnRegresar.setText("Regresar");
        add(btnRegresar);
        btnRegresar.setBounds(270, 380, 165, 35);

        btnRealizarPago.setText("Realizar Pago");
        add(btnRealizarPago);
        btnRealizarPago.setBounds(490, 380, 146, 35);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblCodigoMedi() {
        return lblCodigoMedi;
    }

    public JLabel getLblConsumo() {
        return lblConsumoDiam;
    }

    public JLabel getLblFcehaInic() {
        return lblFcehaInic;
    }

    public JLabel getLblFechaFin() {
        return lblFechaFin;
    }

    public JLabel getLblPropietario() {
        return lblPropietario;
    }

    public JButton getBtnRealizarPago() {
        return btnRealizarPago;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JLabel getLblConsumoDiam() {
        return lblConsumoDiam;
    }

    public JLabel getLblConsumoDin() {
        return lblConsumoDin;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblLimitePago() {
        return lblLimitePago;
    }

    public JLabel getLblMontoNeto() {
        return lblMontoNeto;
    }

    public JLabel getLblMontoServ() {
        return lblMontoServ;
    }

    public JLabel getLblMora() {
        return lblMora;
    }

    public JLabel getLblTotal() {
        return lblTotal;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarPago;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCodigoMedi;
    private javax.swing.JLabel lblConsumoDiam;
    private javax.swing.JLabel lblConsumoDin;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFcehaInic;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblLimitePago;
    private javax.swing.JLabel lblMontoNeto;
    private javax.swing.JLabel lblMontoServ;
    private javax.swing.JLabel lblMora;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
